//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.18033
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthService
{
    using System.Runtime.Serialization;
    using System;
    
    
    /// <summary>Autentifikační token.</summary>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthToken", Namespace="https://ws8websecdb.upc.cz/AuthService")]
    [System.SerializableAttribute()]
    public partial class AuthToken : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <summary>Hodnota tokenu zakódována v base-64.</summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ValueField, value) != true))
                {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <summary>Výsledek autentifikace.</summary>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthResult", Namespace="https://ws8websecdb.upc.cz/AuthService")]
    [System.SerializableAttribute()]
    public partial class AuthResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short StatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UnsuccessfulAttemptsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <summary>Aplikační identifikátor.</summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppId
        {
            get
            {
                return this.AppIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AppIdField, value) != true))
                {
                    this.AppIdField = value;
                    this.RaisePropertyChanged("AppId");
                }
            }
        }
        
        /// <summary>Popis statusu.</summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc
        {
            get
            {
                return this.StatusDescField;
            }
            set
            {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true))
                {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
        
        /// <summary>ID statusu: 0 - proces neúspěšný, 1 - autentifikace úspěšná, 2 - uživatel nenalezen, 3 - nesprávné heslo.</summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short StatusId
        {
            get
            {
                return this.StatusIdField;
            }
            set
            {
                if ((this.StatusIdField.Equals(value) != true))
                {
                    this.StatusIdField = value;
                    this.RaisePropertyChanged("StatusId");
                }
            }
        }
        
        /// <summary>Počet neúspěšných pokusů.</summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnsuccessfulAttempts
        {
            get
            {
                return this.UnsuccessfulAttemptsField;
            }
            set
            {
                if ((this.UnsuccessfulAttemptsField.Equals(value) != true))
                {
                    this.UnsuccessfulAttemptsField = value;
                    this.RaisePropertyChanged("UnsuccessfulAttempts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <summary>Data uživatele.</summary>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="https://ws8websecdb.upc.cz/AuthService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <summary>Aplikační identifikátor.</summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppId
        {
            get
            {
                return this.AppIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AppIdField, value) != true))
                {
                    this.AppIdField = value;
                    this.RaisePropertyChanged("AppId");
                }
            }
        }
        
        /// <summary>Přihlašovací údaj.</summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login
        {
            get
            {
                return this.LoginField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LoginField, value) != true))
                {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        /// <summary>Heslo.</summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PasswordField, value) != true))
                {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <summary>Výsledek registrace.</summary>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegResult", Namespace="https://ws8websecdb.upc.cz/AuthService")]
    [System.SerializableAttribute()]
    public partial class RegResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short StatusIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        /// <summary>Popis statusu.</summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc
        {
            get
            {
                return this.StatusDescField;
            }
            set
            {
                if ((object.ReferenceEquals(this.StatusDescField, value) != true))
                {
                    this.StatusDescField = value;
                    this.RaisePropertyChanged("StatusDesc");
                }
            }
        }
        
        /// <summary>ID statusu: 0 - registrace neúspěšná, 1 - úspěšná registrace, 2 - registrace neúspěšná, uživatel již existuje.</summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short StatusId
        {
            get
            {
                return this.StatusIdField;
            }
            set
            {
                if ((this.StatusIdField.Equals(value) != true))
                {
                    this.StatusIdField = value;
                    this.RaisePropertyChanged("StatusId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <summary>Autentifikační služba.</summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ws8websecdb.upc.cz/AuthService", ConfigurationName="AuthService.IAuthSvc")]
    public interface IAuthSvc
    {
        
        // CODEGEN: Probíhá generování kontraktu zprávy, protože ve zprávě LoginResponse se nacházejí záhlaví
        /// <summary>Autentifikace.</summary>
        /// <param name="loginName">Přihlašovací údaj.</param>
        /// <param name="password">Heslo.</param>
        /// <param name="sourceId">Identifikace zdroje, např. IP adresa.</param>
        /// <returns>Výsledek autentifikace.</returns>
        [System.ServiceModel.OperationContractAttribute(Action="https://ws8websecdb.upc.cz/AuthService/IAuthSvc/Login", ReplyAction="https://ws8websecdb.upc.cz/AuthService/IAuthSvc/LoginResponse")]
        AuthService.LoginResponse Login(AuthService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws8websecdb.upc.cz/AuthService/IAuthSvc/Login", ReplyAction="https://ws8websecdb.upc.cz/AuthService/IAuthSvc/LoginResponse")]
        System.Threading.Tasks.Task<AuthService.LoginResponse> LoginAsync(AuthService.LoginRequest request);
        
        // CODEGEN: Probíhá generování kontraktu zprávy, protože ve zprávě ChangePasswordRequest se nacházejí záhlaví
        /// <summary>Změna hesla.</summary>
        /// <param name="loginName">Přihlašovací údaj.</param>
        /// <param name="curPwd">Aktuální heslo.</param>
        /// <param name="newPwd">Nové heslo.</param>
        /// <returns>True, byla-li změna úspěšná, jinak false.</returns>
        [System.ServiceModel.OperationContractAttribute(Action="https://ws8websecdb.upc.cz/AuthService/IAuthSvc/ChangePassword", ReplyAction="https://ws8websecdb.upc.cz/AuthService/IAuthSvc/ChangePasswordResponse")]
        AuthService.ChangePasswordResponse ChangePassword(AuthService.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws8websecdb.upc.cz/AuthService/IAuthSvc/ChangePassword", ReplyAction="https://ws8websecdb.upc.cz/AuthService/IAuthSvc/ChangePasswordResponse")]
        System.Threading.Tasks.Task<AuthService.ChangePasswordResponse> ChangePasswordAsync(AuthService.ChangePasswordRequest request);
        
        // CODEGEN: Probíhá generování kontraktu zprávy, protože ve zprávě RegisterResponse se nacházejí záhlaví
        /// <summary>Registace uživatele.</summary>
        /// <param name="user">Data uživatele.</param>
        /// <returns>Výsledek registrace.</returns>
        [System.ServiceModel.OperationContractAttribute(Action="https://ws8websecdb.upc.cz/AuthService/IAuthSvc/Register", ReplyAction="https://ws8websecdb.upc.cz/AuthService/IAuthSvc/RegisterResponse")]
        AuthService.RegisterResponse Register(AuthService.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws8websecdb.upc.cz/AuthService/IAuthSvc/Register", ReplyAction="https://ws8websecdb.upc.cz/AuthService/IAuthSvc/RegisterResponse")]
        System.Threading.Tasks.Task<AuthService.RegisterResponse> RegisterAsync(AuthService.RegisterRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="https://ws8websecdb.upc.cz/AuthService", IsWrapped=true)]
    public partial class LoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ws8websecdb.upc.cz/AuthService", Order=0)]
        public string loginName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ws8websecdb.upc.cz/AuthService", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ws8websecdb.upc.cz/AuthService", Order=2)]
        public string sourceId;
        
        public LoginRequest()
        {
        }
        
        public LoginRequest(string loginName, string password, string sourceId)
        {
            this.loginName = loginName;
            this.password = password;
            this.sourceId = sourceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="https://ws8websecdb.upc.cz/AuthService", IsWrapped=true)]
    public partial class LoginResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://ws8websecdb.upc.cz/AuthService")]
        public AuthService.AuthToken AuthToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ws8websecdb.upc.cz/AuthService", Order=0)]
        public AuthService.AuthResult LoginResult;
        
        public LoginResponse()
        {
        }
        
        public LoginResponse(AuthService.AuthToken AuthToken, AuthService.AuthResult LoginResult)
        {
            this.AuthToken = AuthToken;
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePassword", WrapperNamespace="https://ws8websecdb.upc.cz/AuthService", IsWrapped=true)]
    public partial class ChangePasswordRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://ws8websecdb.upc.cz/AuthService")]
        public AuthService.AuthToken AuthToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ws8websecdb.upc.cz/AuthService", Order=0)]
        public string loginName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ws8websecdb.upc.cz/AuthService", Order=1)]
        public string curPwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ws8websecdb.upc.cz/AuthService", Order=2)]
        public string newPwd;
        
        public ChangePasswordRequest()
        {
        }
        
        public ChangePasswordRequest(AuthService.AuthToken AuthToken, string loginName, string curPwd, string newPwd)
        {
            this.AuthToken = AuthToken;
            this.loginName = loginName;
            this.curPwd = curPwd;
            this.newPwd = newPwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePasswordResponse", WrapperNamespace="https://ws8websecdb.upc.cz/AuthService", IsWrapped=true)]
    public partial class ChangePasswordResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://ws8websecdb.upc.cz/AuthService")]
        public AuthService.AuthToken AuthToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ws8websecdb.upc.cz/AuthService", Order=0)]
        public bool ChangePasswordResult;
        
        public ChangePasswordResponse()
        {
        }
        
        public ChangePasswordResponse(AuthService.AuthToken AuthToken, bool ChangePasswordResult)
        {
            this.AuthToken = AuthToken;
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Register", WrapperNamespace="https://ws8websecdb.upc.cz/AuthService", IsWrapped=true)]
    public partial class RegisterRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ws8websecdb.upc.cz/AuthService", Order=0)]
        public AuthService.User user;
        
        public RegisterRequest()
        {
        }
        
        public RegisterRequest(AuthService.User user)
        {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterResponse", WrapperNamespace="https://ws8websecdb.upc.cz/AuthService", IsWrapped=true)]
    public partial class RegisterResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://ws8websecdb.upc.cz/AuthService")]
        public AuthService.AuthToken AuthToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ws8websecdb.upc.cz/AuthService", Order=0)]
        public AuthService.RegResult RegisterResult;
        
        public RegisterResponse()
        {
        }
        
        public RegisterResponse(AuthService.AuthToken AuthToken, AuthService.RegResult RegisterResult)
        {
            this.AuthToken = AuthToken;
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthSvcChannel : AuthService.IAuthSvc, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthSvcClient : System.ServiceModel.ClientBase<AuthService.IAuthSvc>, AuthService.IAuthSvc
    {
        
        public AuthSvcClient()
        {
        }
        
        public AuthSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public AuthSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AuthSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AuthSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AuthService.LoginResponse AuthService.IAuthSvc.Login(AuthService.LoginRequest request)
        {
            return base.Channel.Login(request);
        }
        
        public AuthService.AuthToken Login(string loginName, string password, string sourceId, out AuthService.AuthResult LoginResult)
        {
            AuthService.LoginRequest inValue = new AuthService.LoginRequest();
            inValue.loginName = loginName;
            inValue.password = password;
            inValue.sourceId = sourceId;
            AuthService.LoginResponse retVal = ((AuthService.IAuthSvc)(this)).Login(inValue);
            LoginResult = retVal.LoginResult;
            return retVal.AuthToken;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthService.LoginResponse> AuthService.IAuthSvc.LoginAsync(AuthService.LoginRequest request)
        {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthService.LoginResponse> LoginAsync(string loginName, string password, string sourceId)
        {
            AuthService.LoginRequest inValue = new AuthService.LoginRequest();
            inValue.loginName = loginName;
            inValue.password = password;
            inValue.sourceId = sourceId;
            return ((AuthService.IAuthSvc)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AuthService.ChangePasswordResponse AuthService.IAuthSvc.ChangePassword(AuthService.ChangePasswordRequest request)
        {
            return base.Channel.ChangePassword(request);
        }
        
        public bool ChangePassword(ref AuthService.AuthToken AuthToken, string loginName, string curPwd, string newPwd)
        {
            AuthService.ChangePasswordRequest inValue = new AuthService.ChangePasswordRequest();
            inValue.AuthToken = AuthToken;
            inValue.loginName = loginName;
            inValue.curPwd = curPwd;
            inValue.newPwd = newPwd;
            AuthService.ChangePasswordResponse retVal = ((AuthService.IAuthSvc)(this)).ChangePassword(inValue);
            AuthToken = retVal.AuthToken;
            return retVal.ChangePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthService.ChangePasswordResponse> AuthService.IAuthSvc.ChangePasswordAsync(AuthService.ChangePasswordRequest request)
        {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthService.ChangePasswordResponse> ChangePasswordAsync(AuthService.AuthToken AuthToken, string loginName, string curPwd, string newPwd)
        {
            AuthService.ChangePasswordRequest inValue = new AuthService.ChangePasswordRequest();
            inValue.AuthToken = AuthToken;
            inValue.loginName = loginName;
            inValue.curPwd = curPwd;
            inValue.newPwd = newPwd;
            return ((AuthService.IAuthSvc)(this)).ChangePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AuthService.RegisterResponse AuthService.IAuthSvc.Register(AuthService.RegisterRequest request)
        {
            return base.Channel.Register(request);
        }
        
        public AuthService.AuthToken Register(AuthService.User user, out AuthService.RegResult RegisterResult)
        {
            AuthService.RegisterRequest inValue = new AuthService.RegisterRequest();
            inValue.user = user;
            AuthService.RegisterResponse retVal = ((AuthService.IAuthSvc)(this)).Register(inValue);
            RegisterResult = retVal.RegisterResult;
            return retVal.AuthToken;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AuthService.RegisterResponse> AuthService.IAuthSvc.RegisterAsync(AuthService.RegisterRequest request)
        {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<AuthService.RegisterResponse> RegisterAsync(AuthService.User user)
        {
            AuthService.RegisterRequest inValue = new AuthService.RegisterRequest();
            inValue.user = user;
            return ((AuthService.IAuthSvc)(this)).RegisterAsync(inValue);
        }
    }
}
